var metaList = [
{"speciesName":"Mute Swan","latinName":"Cygnus olor","conservationStatus":"Amber"},
{"speciesName":"Black Swan","latinName":"Cygnus atratus","conservationStatus":""},
{"speciesName":"Bewick's Swan","latinName":"Cygnus columbianus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Whooper Swan","latinName":"Cygnus cygnus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Pink-footed Goose","latinName":"Anser brachyrhynchus","conservationStatus":"Amber"},
{"speciesName":"White-fronted Goose","latinName":"Anser albifrons","conservationStatus":"Red"},
{"speciesName":"Greylag Goose","latinName":"Anser anser","conservationStatus":"Amber"},
{"speciesName":"Bar-headed Goose","latinName":"Anser indicus","conservationStatus":""},
{"speciesName":"Snow Goose","latinName":"Anser caerulescens","conservationStatus":""},
{"speciesName":"Canada Goose","latinName":"Branta canadensis","conservationStatus":""},
{"speciesName":"Barnacle Goose","latinName":"Branta leucopsis","conservationStatus":"Amber"},
{"speciesName":"Brent Goose","latinName":"Branta bernicla","conservationStatus":"Amber"},
{"speciesName":"Red-breasted Goose","latinName":"Branta ruficollis","conservationStatus":""},
{"speciesName":"Egyptian Goose","latinName":"Alopochen aegyptiaca","conservationStatus":""},
{"speciesName":"Ruddy Shelduck","latinName":"Tadorna ferruginea","conservationStatus":""},
{"speciesName":"Shelduck","latinName":"Tadorna tadorna","conservationStatus":"Amber"},
{"speciesName":"Wood Duck","latinName":"Aix sponsa","conservationStatus":""},
{"speciesName":"Mandarin","latinName":"Aix galericulata","conservationStatus":""},
{"speciesName":"Wigeon","latinName":"Anas penelope","conservationStatus":"Amber"},
{"speciesName":"American Wigeon","latinName":"Anas americana","conservationStatus":""},
{"speciesName":"Gadwall","latinName":"Anas strepera","conservationStatus":"Amber"},
{"speciesName":"Teal","latinName":"Anas crecca","conservationStatus":"Amber"},
{"speciesName":"Green-winged Teal","latinName":"Anas carolinensis","conservationStatus":""},
{"speciesName":"Mallard","latinName":"Anas platyrhynchos","conservationStatus":"Amber"},
{"speciesName":"Pintail","latinName":"Anas acuta","conservationStatus":"Amber"},
{"speciesName":"Garganey","latinName":"Anas querquedula","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Shoveler","latinName":"Anas clypeata","conservationStatus":"Amber"},
{"speciesName":"Red-crested Pochard","latinName":"Netta rufina","conservationStatus":""},
{"speciesName":"Pochard","latinName":"Aythya ferina","conservationStatus":"Red"},
{"speciesName":"Ring-necked Duck","latinName":"Aythya collaris","conservationStatus":""},
{"speciesName":"Tufted Duck","latinName":"Aythya fuligula","conservationStatus":"Amber"},
{"speciesName":"Scaup","latinName":"Aythya marila","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Eider","latinName":"Somateria mollissima","conservationStatus":"Amber"},
{"speciesName":"Long-tailed Duck","latinName":"Clangula hyemalis","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Common Scoter","latinName":"Melanitta nigra","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Velvet Scoter","latinName":"Melanitta fusca","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Goldeneye","latinName":"Bucephala clangula","conservationStatus":"Amber"},
{"speciesName":"Smew","latinName":"Mergellus albellus","conservationStatus":"Amber"},
{"speciesName":"Red-breasted Merganser","latinName":"Mergus serrator","conservationStatus":""},
{"speciesName":"Goosander","latinName":"Mergus merganser","conservationStatus":""},
{"speciesName":"Ruddy Duck","latinName":"Oxyura jamaicensis","conservationStatus":""},
{"speciesName":"Black Grouse","latinName":"Tetrao tetrix","conservationStatus":""},
{"speciesName":"Red-legged Partridge","latinName":"Alectoris rufa","conservationStatus":""},
{"speciesName":"Grey Partridge","latinName":"Perdix perdix","conservationStatus":"Red"},
{"speciesName":"Quail","latinName":"Coturnix coturnix","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Pheasant","latinName":"Phasianus colchicus","conservationStatus":""},
{"speciesName":"Golden Pheasant","latinName":"Chrysolophus pictus","conservationStatus":""},
{"speciesName":"Lady Amherst's Pheasant","latinName":"Chrysolophus amherstiae","conservationStatus":""},
{"speciesName":"Red Grouse","latinName":"","conservationStatus":"Amber"},
{"speciesName":"Great Northern Diver","latinName":"Gavia immer","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Fulmar","latinName":"Fulmarus glacialis","conservationStatus":"Amber"},
{"speciesName":"Manx Shearwater","latinName":"Puffinus puffinus","conservationStatus":"Amber"},
{"speciesName":"Storm Petrel","latinName":"Hydrobates pelagicus","conservationStatus":"Amber"},
{"speciesName":"Leach's Petrel","latinName":"Oceanodroma leucorhoa","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Gannet","latinName":"Morus bassanus","conservationStatus":"Amber"},
{"speciesName":"Cormorant","latinName":"Phalacrocorax carbo","conservationStatus":""},
{"speciesName":"Shag","latinName":"Phalacrocorax aristotelis","conservationStatus":"Red"},
{"speciesName":"Bittern","latinName":"Botaurus stellaris","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Cattle Egret","latinName":"Bubulcus ibis","conservationStatus":""},
{"speciesName":"Little Egret","latinName":"Egretta garzetta","conservationStatus":"Schedule 1"},
{"speciesName":"Great White Egret","latinName":"Ardea alba","conservationStatus":""},
{"speciesName":"Grey Heron","latinName":"Ardea cinerea","conservationStatus":""},
{"speciesName":"Purple Heron","latinName":"Ardea purpurea","conservationStatus":"Schedule 1"},
{"speciesName":"White Stork","latinName":"Ciconia ciconia","conservationStatus":""},
{"speciesName":"Glossy Ibis","latinName":"Plegadis falcinellus","conservationStatus":""},
{"speciesName":"Spoonbill","latinName":"Platalea leucorodia","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Little Grebe","latinName":"Tachybaptus ruficollis","conservationStatus":"Amber"},
{"speciesName":"Great Crested Grebe","latinName":"Podiceps cristatus","conservationStatus":""},
{"speciesName":"Red-necked Grebe","latinName":"Podiceps grisegena","conservationStatus":"Red"},
{"speciesName":"Slavonian Grebe","latinName":"Podiceps auritus","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Black-necked Grebe","latinName":"Podiceps nigricollis","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Black Kite","latinName":"Milvus migrans","conservationStatus":""},
{"speciesName":"Red Kite","latinName":"Milvus milvus","conservationStatus":"Schedule 1"},
{"speciesName":"Marsh Harrier","latinName":"Circus aeruginosus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Hen Harrier","latinName":"Circus cyaneus","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Montagu's Harrier","latinName":"Circus pygargus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Goshawk","latinName":"Accipiter gentilis","conservationStatus":"Schedule 1"},
{"speciesName":"Sparrowhawk","latinName":"Accipiter nisus","conservationStatus":""},
{"speciesName":"Buzzard","latinName":"Buteo buteo","conservationStatus":""},
{"speciesName":"Rough-legged Buzzard","latinName":"Buteo lagopus","conservationStatus":""},
{"speciesName":"Osprey","latinName":"Pandion haliaetus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Kestrel","latinName":"Falco tinnunculus","conservationStatus":"Amber"},
{"speciesName":"Red-footed Falcon","latinName":"Falco vespertinus","conservationStatus":""},
{"speciesName":"Merlin","latinName":"Falco columbarius","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Hobby","latinName":"Falco subbuteo","conservationStatus":"Schedule 1"},
{"speciesName":"Gyr Falcon","latinName":"Falco rusticolus","conservationStatus":"Schedule 1"},
{"speciesName":"Peregrine","latinName":"Falco peregrinus","conservationStatus":"Schedule 1"},
{"speciesName":"Water Rail","latinName":"Rallus aquaticus","conservationStatus":""},
{"speciesName":"Spotted Crake","latinName":"Porzana porzana","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Corncrake","latinName":"Crex crex","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Moorhen","latinName":"Gallinula chloropus","conservationStatus":""},
{"speciesName":"Coot","latinName":"Fulica atra","conservationStatus":""},
{"speciesName":"Crane","latinName":"Grus grus","conservationStatus":"Amber"},
{"speciesName":"Great Bustard","latinName":"Otis tarda","conservationStatus":""},
{"speciesName":"Stone Curlew","latinName":"Burhinus oedicnemus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Black-winged Stilt","latinName":"Himantopus himantopus","conservationStatus":"Schedule 1"},
{"speciesName":"Avocet","latinName":"Recurvirostra avosetta","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Oystercatcher","latinName":"Haematopus ostralegus","conservationStatus":"Amber"},
{"speciesName":"Golden Plover","latinName":"Pluvialis apricaria","conservationStatus":"Amber"},
{"speciesName":"Grey Plover","latinName":"Pluvialis squatarola","conservationStatus":"Amber"},
{"speciesName":"Lapwing","latinName":"Vanellus vanellus","conservationStatus":"Red"},
{"speciesName":"Little Ringed Plover","latinName":"Charadrius dubius","conservationStatus":"Schedule 1"},
{"speciesName":"Ringed Plover","latinName":"Charadrius hiaticula","conservationStatus":"Red"},
{"speciesName":"Kentish Plover","latinName":"Charadrius alexandrinus","conservationStatus":"Schedule 1"},
{"speciesName":"Dotterel","latinName":"Charadrius morinellus","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Whimbrel","latinName":"Numenius phaeopus","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Curlew","latinName":"Numenius arquata","conservationStatus":"Red"},
{"speciesName":"Black-tailed Godwit","latinName":"Limosa limosa","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Bar-tailed Godwit","latinName":"Limosa lapponica","conservationStatus":"Amber"},
{"speciesName":"Turnstone","latinName":"Arenaria interpres","conservationStatus":"Amber"},
{"speciesName":"Knot","latinName":"Calidris canutus","conservationStatus":"Amber"},
{"speciesName":"Ruff","latinName":"Philomachus pugnax","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Curlew Sandpiper","latinName":"Calidris ferruginea","conservationStatus":""},
{"speciesName":"Sanderling","latinName":"Calidris alba","conservationStatus":""},
{"speciesName":"Dunlin","latinName":"Calidris alpina","conservationStatus":"Amber"},
{"speciesName":"Purple Sandpiper","latinName":"Calidris maritima","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Little Stint","latinName":"Calidris minuta","conservationStatus":""},
{"speciesName":"Pectoral Sandpiper","latinName":"Calidris melanotos","conservationStatus":""},
{"speciesName":"Wilson's Phalarope","latinName":"Phalaropus tricolor","conservationStatus":""},
{"speciesName":"Red-necked Phalarope","latinName":"Phalaropus lobatus","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Grey Phalarope","latinName":"Phalaropus fulicarius","conservationStatus":""},
{"speciesName":"Common Sandpiper","latinName":"Actitis hypoleucos","conservationStatus":"Amber"},
{"speciesName":"Green Sandpiper","latinName":"Tringa ochropus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Spotted Redshank","latinName":"Tringa erythropus","conservationStatus":"Amber"},
{"speciesName":"Greenshank","latinName":"Tringa nebularia","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Lesser Yellowlegs","latinName":"Tringa flavipes","conservationStatus":""},
{"speciesName":"Marsh Sandpiper","latinName":"Tringa stagnatilis","conservationStatus":""},
{"speciesName":"Wood Sandpiper","latinName":"Tringa glareola","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Redshank","latinName":"Tringa totanus","conservationStatus":"Amber"},
{"speciesName":"Jack Snipe","latinName":"Lymnocryptes minimus","conservationStatus":"Amber"},
{"speciesName":"Woodcock","latinName":"Scolopax rusticola","conservationStatus":"Red"},
{"speciesName":"Snipe","latinName":"Gallinago gallinago","conservationStatus":"Amber"},
{"speciesName":"Pomarine Skua","latinName":"Stercorarius pomarinus","conservationStatus":""},
{"speciesName":"Arctic Skua","latinName":"Stercorarius parasiticus","conservationStatus":"Red"},
{"speciesName":"Long-tailed Skua","latinName":"Stercorarius longicaudus","conservationStatus":""},
{"speciesName":"Great Skua","latinName":"Stercorarius skua","conservationStatus":"Amber"},
{"speciesName":"Puffin","latinName":"Fratercula arctica","conservationStatus":"Red"},
{"speciesName":"Razorbill","latinName":"Alca torda","conservationStatus":"Amber"},
{"speciesName":"Little Auk","latinName":"Alle alle","conservationStatus":""},
{"speciesName":"Guillemot","latinName":"Uria aalge","conservationStatus":"Amber"},
{"speciesName":"Black Guillemot","latinName":"","conservationStatus":"Amber"},
{"speciesName":"Little Tern","latinName":"Sternula albifrons","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Whiskered Tern","latinName":"Chlidonias hybrida","conservationStatus":""},
{"speciesName":"Black Tern","latinName":"Chlidonias niger","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"White-winged Black Tern","latinName":"Chlidonias leucopterus","conservationStatus":""},
{"speciesName":"Sandwich Tern","latinName":"Sterna sandvicensis","conservationStatus":"Amber"},
{"speciesName":"Common Tern","latinName":"Sterna hirundo","conservationStatus":"Amber"},
{"speciesName":"Roseate Tern","latinName":"Sterna dougallii","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Arctic Tern","latinName":"Sterna paradisaea","conservationStatus":"Amber"},
{"speciesName":"Sabine's Gull","latinName":"Xema sabini","conservationStatus":""},
{"speciesName":"Kittiwake","latinName":"Rissa tridactyla","conservationStatus":"Red"},
{"speciesName":"Bonaparte's Gull","latinName":"Chroicocephalus philadelphia","conservationStatus":""},
{"speciesName":"Black-headed Gull","latinName":"Chroicocephalus ridibundus","conservationStatus":"Amber"},
{"speciesName":"Little Gull","latinName":"Hydrocoloeus minutus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Laughing Gull","latinName":"Larus atricilla","conservationStatus":""},
{"speciesName":"Mediterranean Gull","latinName":"Larus melanocephalus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Common Gull","latinName":"Larus canus","conservationStatus":"Amber"},
{"speciesName":"Ring-billed Gull","latinName":"Larus delawarensis","conservationStatus":""},
{"speciesName":"Lesser Black-backed Gull","latinName":"Larus fuscus","conservationStatus":"Amber"},
{"speciesName":"Herring Gull","latinName":"Larus argentatus","conservationStatus":"Red"},
{"speciesName":"Caspian Gull","latinName":"Larus cachinnans","conservationStatus":"Amber"},
{"speciesName":"Iceland Gull","latinName":"Larus glaucoides","conservationStatus":"Amber"},
{"speciesName":"Glaucous Gull","latinName":"Larus hyperboreus","conservationStatus":"Amber"},
{"speciesName":"Great Black-backed Gull","latinName":"Larus marinus","conservationStatus":"Amber"},
{"speciesName":"Feral Pigeon","latinName":"Columba livia","conservationStatus":""},
{"speciesName":"Stock Dove","latinName":"Columba oenas","conservationStatus":"Amber"},
{"speciesName":"Woodpigeon","latinName":"Columba palumbus","conservationStatus":""},
{"speciesName":"Collared Dove","latinName":"Streptopelia decaocto","conservationStatus":""},
{"speciesName":"Turtle Dove","latinName":"Streptopelia turtur","conservationStatus":"Red"},
{"speciesName":"Ring-necked Parakeet","latinName":"Psittacula krameri","conservationStatus":""},
{"speciesName":"Cuckoo","latinName":"Cuculus canorus","conservationStatus":"Red"},
{"speciesName":"Barn Owl","latinName":"Tyto alba","conservationStatus":"Schedule 1"},
{"speciesName":"Little Owl","latinName":"Athene noctua","conservationStatus":""},
{"speciesName":"Tawny Owl","latinName":"Strix aluco","conservationStatus":"Amber"},
{"speciesName":"Long-eared Owl","latinName":"Asio otus","conservationStatus":""},
{"speciesName":"Short-eared Owl","latinName":"Asio flammeus","conservationStatus":"Amber"},
{"speciesName":"Nightjar","latinName":"Caprimulgus europaeus","conservationStatus":"Amber"},
{"speciesName":"Swift","latinName":"Apus apus","conservationStatus":"Amber"},
{"speciesName":"Alpine Swift","latinName":"Apus melba","conservationStatus":""},
{"speciesName":"Kingfisher","latinName":"Alcedo atthis","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Hoopoe","latinName":"Upupa epops","conservationStatus":"Schedule 1"},
{"speciesName":"Wryneck","latinName":"Jynx torquilla","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Green Woodpecker","latinName":"Picus viridis","conservationStatus":"Amber"},
{"speciesName":"Great Spotted Woodpecker","latinName":"Dendrocopos major","conservationStatus":""},
{"speciesName":"Lesser Spotted Woodpecker","latinName":"Dendrocopos minor","conservationStatus":"Red"},
{"speciesName":"Golden Oriole","latinName":"Oriolus oriolus","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Red-backed Shrike","latinName":"Lanius collurio","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Great Grey Shrike","latinName":"Lanius excubitor","conservationStatus":""},
{"speciesName":"Woodchat Shrike","latinName":"Lanius senator","conservationStatus":""},
{"speciesName":"Chough","latinName":"Pyrrhocorax pyrrhocorax","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Magpie","latinName":"Pica pica","conservationStatus":""},
{"speciesName":"Jay","latinName":"Garrulus glandarius","conservationStatus":""},
{"speciesName":"Jackdaw","latinName":"Corvus monedula","conservationStatus":""},
{"speciesName":"Rook","latinName":"Corvus frugilegus","conservationStatus":""},
{"speciesName":"Carrion Crow","latinName":"Corvus corone","conservationStatus":""},
{"speciesName":"Hooded Crow","latinName":"Corvus cornix","conservationStatus":""},
{"speciesName":"Raven","latinName":"Corvus corax","conservationStatus":""},
{"speciesName":"Goldcrest","latinName":"Regulus regulus","conservationStatus":""},
{"speciesName":"Firecrest","latinName":"Regulus ignicapilla","conservationStatus":"Schedule 1"},
{"speciesName":"Penduline Tit","latinName":"Remiz pendulinus","conservationStatus":""},
{"speciesName":"Blue Tit","latinName":"Cyanistes caeruleus","conservationStatus":""},
{"speciesName":"Great Tit","latinName":"Parus major","conservationStatus":""},
{"speciesName":"Coal Tit","latinName":"Periparus ater","conservationStatus":""},
{"speciesName":"Willow Tit","latinName":"Poecile montana","conservationStatus":"Red"},
{"speciesName":"Marsh Tit","latinName":"Poecile palustris","conservationStatus":"Red"},
{"speciesName":"Bearded Tit","latinName":"Panurus biarmicus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Short-toed Lark","latinName":"Calandrella brachydactyla","conservationStatus":""},
{"speciesName":"Woodlark","latinName":"Lullula arborea","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Skylark","latinName":"Alauda arvensis","conservationStatus":"Red"},
{"speciesName":"Sand Martin","latinName":"Riparia riparia","conservationStatus":"Amber"},
{"speciesName":"Swallow","latinName":"Hirundo rustica","conservationStatus":"Amber"},
{"speciesName":"House Martin","latinName":"Delichon urbicum","conservationStatus":"Amber"},
{"speciesName":"Red-rumped Swallow","latinName":"Cecropis daurica","conservationStatus":""},
{"speciesName":"Cetti's Warbler","latinName":"Cettia cetti","conservationStatus":"Schedule 1"},
{"speciesName":"Long-tailed Tit","latinName":"Aegithalos caudatus","conservationStatus":""},
{"speciesName":"Pallas's Warbler","latinName":"Phylloscopus proregulus","conservationStatus":""},
{"speciesName":"Yellow-browed Warbler","latinName":"Phylloscopus inornatus","conservationStatus":""},
{"speciesName":"Western Bonelli's Warbler","latinName":"Phylloscopus bonelli","conservationStatus":""},
{"speciesName":"Wood Warbler","latinName":"Phylloscopus sibilatrix","conservationStatus":"Red"},
{"speciesName":"Chiffchaff","latinName":"Phylloscopus collybita","conservationStatus":""},
{"speciesName":"Willow Warbler","latinName":"Phylloscopus trochilus","conservationStatus":"Amber"},
{"speciesName":"Blackcap","latinName":"Sylvia atricapilla","conservationStatus":""},
{"speciesName":"Garden Warbler","latinName":"Sylvia borin","conservationStatus":""},
{"speciesName":"Lesser Whitethroat","latinName":"Sylvia curruca","conservationStatus":""},
{"speciesName":"Whitethroat","latinName":"Sylvia communis","conservationStatus":"Amber"},
{"speciesName":"Dartford Warbler","latinName":"Sylvia undata","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Grasshopper Warbler","latinName":"Locustella naevia","conservationStatus":"Red"},
{"speciesName":"Savi's Warbler","latinName":"Locustella luscinioides","conservationStatus":""},
{"speciesName":"Icterine Warbler","latinName":"Hippolais icterina","conservationStatus":""},
{"speciesName":"Melodious Warbler","latinName":"Hippolais polyglotta","conservationStatus":""},
{"speciesName":"Aquatic Warbler","latinName":"Acrocephalus paludicola","conservationStatus":"Red"},
{"speciesName":"Sedge Warbler","latinName":"Acrocephalus schoenobaenus","conservationStatus":""},
{"speciesName":"Paddyfield Warbler","latinName":"Acrocephalus agricola","conservationStatus":""},
{"speciesName":"Marsh Warbler","latinName":"Acrocephalus palustris","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Reed Warbler","latinName":"Acrocephalus scirpaceus","conservationStatus":""},
{"speciesName":"Great Reed Warbler","latinName":"Acrocephalus arundinaceus","conservationStatus":""},
{"speciesName":"Waxwing","latinName":"Bombycilla garrulus","conservationStatus":""},
{"speciesName":"Nuthatch","latinName":"Sitta europaea","conservationStatus":""},
{"speciesName":"Treecreeper","latinName":"Certhia familiaris","conservationStatus":""},
{"speciesName":"Wren","latinName":"Troglodytes troglodytes","conservationStatus":""},
{"speciesName":"Starling","latinName":"Sturnus vulgaris","conservationStatus":"Red"},
{"speciesName":"Rose-coloured Starling","latinName":"Pastor roseus","conservationStatus":""},
{"speciesName":"Dipper","latinName":"Cinclus cinclus","conservationStatus":"Amber"},
{"speciesName":"Ring Ouzel","latinName":"Turdus torquatus","conservationStatus":"Red"},
{"speciesName":"Blackbird","latinName":"Turdus merula","conservationStatus":""},
{"speciesName":"Black-throated Thrush","latinName":"Turdus atrogularis","conservationStatus":""},
{"speciesName":"Fieldfare","latinName":"Turdus pilaris","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Song Thrush","latinName":"Turdus philomelos","conservationStatus":"Red"},
{"speciesName":"Redwing","latinName":"Turdus iliacus","conservationStatus":"Red"},
{"speciesName":"Mistle Thrush","latinName":"Turdus viscivorus","conservationStatus":"Red"},
{"speciesName":"Spotted Flycatcher","latinName":"Muscicapa striata","conservationStatus":"Red"},
{"speciesName":"Robin","latinName":"Erithacus rubecula","conservationStatus":""},
{"speciesName":"Nightingale","latinName":"Luscinia megarhynchos","conservationStatus":"Red"},
{"speciesName":"Bluethroat","latinName":"Luscinia svecica","conservationStatus":"Schedule 1"},
{"speciesName":"Pied Flycatcher","latinName":"Ficedula hypoleuca","conservationStatus":"Red"},
{"speciesName":"Black Redstart","latinName":"Phoenicurus ochruros","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Redstart","latinName":"Phoenicurus phoenicurus","conservationStatus":"Amber"},
{"speciesName":"Whinchat","latinName":"Saxicola rubetra","conservationStatus":"Red"},
{"speciesName":"Siberian Stonechat","latinName":"","conservationStatus":""},
{"speciesName":"Stonechat","latinName":"Saxicola torquatus","conservationStatus":""},
{"speciesName":"Wheatear","latinName":"Oenanthe oenanthe","conservationStatus":"Amber"},
{"speciesName":"Dunnock","latinName":"Prunella modularis","conservationStatus":"Amber"},
{"speciesName":"House Sparrow","latinName":"Passer domesticus","conservationStatus":"Red"},
{"speciesName":"Tree Sparrow","latinName":"Passer montanus","conservationStatus":"Red"},
{"speciesName":"Yellow Wagtail","latinName":"Motacilla flava","conservationStatus":"Red"},
{"speciesName":"Grey Wagtail","latinName":"Motacilla cinerea","conservationStatus":"Red"},
{"speciesName":"Pied Wagtail","latinName":"Motacilla alba","conservationStatus":""},
{"speciesName":"Richard's Pipit","latinName":"Anthus richardi","conservationStatus":""},
{"speciesName":"Tawny Pipit","latinName":"Anthus campestris","conservationStatus":""},
{"speciesName":"Olive-backed Pipit","latinName":"Anthus hodgsoni","conservationStatus":""},
{"speciesName":"Tree Pipit","latinName":"Anthus trivialis","conservationStatus":"Red"},
{"speciesName":"Meadow Pipit","latinName":"Anthus pratensis","conservationStatus":"Amber"},
{"speciesName":"Red-throated Pipit","latinName":"Anthus cervinus","conservationStatus":""},
{"speciesName":"Rock Pipit","latinName":"Anthus petrosus","conservationStatus":""},
{"speciesName":"Water Pipit","latinName":"Anthus spinoletta","conservationStatus":"Amber"},
{"speciesName":"Chaffinch","latinName":"Fringilla coelebs","conservationStatus":""},
{"speciesName":"Brambling","latinName":"Fringilla montifringilla","conservationStatus":"Schedule 1"},
{"speciesName":"Serin","latinName":"Serinus serinus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Greenfinch","latinName":"Chloris chloris","conservationStatus":""},
{"speciesName":"Goldfinch","latinName":"Carduelis carduelis","conservationStatus":""},
{"speciesName":"Siskin","latinName":"Carduelis spinus","conservationStatus":""},
{"speciesName":"Linnet","latinName":"Carduelis cannabina","conservationStatus":"Red"},
{"speciesName":"Twite","latinName":"Carduelis flavirostris","conservationStatus":"Red"},
{"speciesName":"Lesser Redpoll","latinName":"Carduelis cabaret","conservationStatus":"Red"},
{"speciesName":"Common Rosefinch","latinName":"Carpodacus erythrinus","conservationStatus":"Schedule 1"},
{"speciesName":"Bullfinch","latinName":"Pyrrhula pyrrhula","conservationStatus":"Amber"},
{"speciesName":"Hawfinch","latinName":"Coccothraustes coccothraustes","conservationStatus":"Red"},
{"speciesName":"Snow Bunting","latinName":"Plectrophenax nivalis","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Lapland Bunting","latinName":"Calcarius lapponicus","conservationStatus":"Amber, Schedule 1"},
{"speciesName":"Yellowhammer","latinName":"Emberiza citrinella","conservationStatus":"Red"},
{"speciesName":"Cirl Bunting","latinName":"Emberiza cirlus","conservationStatus":"Red, Schedule 1"},
{"speciesName":"Ortolan Bunting","latinName":"Emberiza hortulana","conservationStatus":""},
{"speciesName":"Little Bunting","latinName":"Emberiza pusilla","conservationStatus":""},
{"speciesName":"Reed Bunting","latinName":"Emberiza schoeniclus","conservationStatus":"Amber"},
{"speciesName":"Corn Bunting","latinName":"Emberiza calandra","conservationStatus":"Red"},
{"speciesName":"American Golden Plover","latinName":"","conservationStatus":""},
{"speciesName":"American Herring Gull","latinName":"","conservationStatus":""},
{"speciesName":"American Robin","latinName":"","conservationStatus":""},
{"speciesName":"Balearic Shearwater","latinName":"","conservationStatus":""},
{"speciesName":"Barred Warbler","latinName":"","conservationStatus":""},
{"speciesName":"Bee-eater","latinName":"","conservationStatus":""},
{"speciesName":"Black Stork","latinName":"","conservationStatus":""},
{"speciesName":"Black-throated Diver","latinName":"","conservationStatus":""},
{"speciesName":"Black-winged Red Bishop","latinName":"","conservationStatus":""},
{"speciesName":"Blue-cheeked Bee-eater","latinName":"","conservationStatus":""},
{"speciesName":"Blythe's Reed Warbler","latinName":"","conservationStatus":""},
{"speciesName":"Booted Warbler","latinName":"","conservationStatus":""},
{"speciesName":"Brent Goose (Black Brant)","latinName":"","conservationStatus":""},
{"speciesName":"Budgerigar","latinName":"","conservationStatus":""},
{"speciesName":"Buff-breasted Sandpiper","latinName":"","conservationStatus":""},
{"speciesName":"Californian Quail","latinName":"","conservationStatus":""},
{"speciesName":"Carrion-Hooded Crow (unspecified)","latinName":"","conservationStatus":""},
{"speciesName":"Chiloe Wigeon","latinName":"","conservationStatus":""},
{"speciesName":"Cockatiel","latinName":"","conservationStatus":""},
{"speciesName":"Common Crossbill","latinName":"","conservationStatus":""},
{"speciesName":"Common Redpoll","latinName":"","conservationStatus":""},
{"speciesName":"Common/Arctic Tern","latinName":"","conservationStatus":""},
{"speciesName":"Common/Lesser Redpoll","latinName":"","conservationStatus":""},
{"speciesName":"Cormorant (Continental)","latinName":"","conservationStatus":""},
{"speciesName":"Cory's Shearwater","latinName":"","conservationStatus":""},
{"speciesName":"Crested Duck","latinName":"","conservationStatus":""},
{"speciesName":"Dark-bellied Brent Goose","latinName":"","conservationStatus":""},
{"speciesName":"Desert Wheatear","latinName":"","conservationStatus":""},
{"speciesName":"Domestic Canary","latinName":"","conservationStatus":""},
{"speciesName":"Domestic Mallard","latinName":"","conservationStatus":""},
{"speciesName":"Dusky Warbler","latinName":"","conservationStatus":""},
{"speciesName":"Eider (Northern - borealis)","latinName":"","conservationStatus":""},
{"speciesName":"Eurasian Eagle-owl","latinName":"","conservationStatus":""},
{"speciesName":"European White-fronted Goose","latinName":"","conservationStatus":""},
{"speciesName":"Falcated Duck","latinName":"","conservationStatus":""},
{"speciesName":"Fea's Petrel","latinName":"","conservationStatus":""},
{"speciesName":"Great Shearwater","latinName":"","conservationStatus":""},
{"speciesName":"Greater Blue-eared Starling","latinName":"","conservationStatus":""},
{"speciesName":"Greenland White-fronted Goose","latinName":"","conservationStatus":""},
{"speciesName":"Greylag Goose (Domestic)","latinName":"","conservationStatus":""},
{"speciesName":"Greylag Goose (naturalised)","latinName":"","conservationStatus":""},
{"speciesName":"Gull-billed Tern","latinName":"","conservationStatus":""},
{"speciesName":"Harris's Hawk","latinName":"","conservationStatus":""},
{"speciesName":"Helmeted Guineafowl","latinName":"","conservationStatus":""},
{"speciesName":"Honey-buzzard","latinName":"","conservationStatus":""},
{"speciesName":"House Finch","latinName":"","conservationStatus":""},
{"speciesName":"Hybrid Duck","latinName":"","conservationStatus":""},
{"speciesName":"Hybrid Goose","latinName":"","conservationStatus":""},
{"speciesName":"Iceland Gull (Kumlien's)","latinName":"","conservationStatus":""},
{"speciesName":"Indian Peafowl","latinName":"","conservationStatus":""},
{"speciesName":"King Eider","latinName":"","conservationStatus":""},
{"speciesName":"Lanner Falcon","latinName":"","conservationStatus":""},
{"speciesName":"Light-bellied Brent Goose","latinName":"","conservationStatus":""},
{"speciesName":"Little Crake","latinName":"","conservationStatus":""},
{"speciesName":"Long-billed Dowitcher","latinName":"","conservationStatus":""},
{"speciesName":"Macaronesian Shearwater","latinName":"","conservationStatus":""},
{"speciesName":"Muscovy Duck","latinName":"","conservationStatus":""},
{"speciesName":"Night-heron","latinName":"","conservationStatus":""},
{"speciesName":"Peach-faced Lovebird","latinName":"","conservationStatus":""},
{"speciesName":"Pied Wheatear","latinName":"","conservationStatus":""},
{"speciesName":"Pied/White Wagtail","latinName":"","conservationStatus":""},
{"speciesName":"Radde's Warbler","latinName":"","conservationStatus":""},
{"speciesName":"Red-breasted Flycatcher","latinName":"","conservationStatus":""},
{"speciesName":"Red-eyed Vireo","latinName":"","conservationStatus":""},
{"speciesName":"Red-flanked Bluetail","latinName":"","conservationStatus":""},
{"speciesName":"Red-throated Diver","latinName":"","conservationStatus":""},
{"speciesName":"Reeve's Pheasant","latinName":"","conservationStatus":""},
{"speciesName":"Ringed Teal","latinName":"","conservationStatus":""},
{"speciesName":"Rock Dove","latinName":"","conservationStatus":""},
{"speciesName":"Rock Pipit (Scandinavian - littoralis)","latinName":"","conservationStatus":""},
{"speciesName":"Sacred Ibis","latinName":"","conservationStatus":""},
{"speciesName":"Saker Falcon","latinName":"","conservationStatus":""},
{"speciesName":"Sardinian Warbler","latinName":"","conservationStatus":""},
{"speciesName":"Semipalmated Sandpiper","latinName":"","conservationStatus":""},
{"speciesName":"Short-toed Eagle","latinName":"","conservationStatus":""},
{"speciesName":"Solitary Sandpiper","latinName":"","conservationStatus":""},
{"speciesName":"Sooty Shearwater","latinName":"","conservationStatus":""},
{"speciesName":"Spotted Sandpiper","latinName":"","conservationStatus":""},
{"speciesName":"Subalpine Warbler","latinName":"","conservationStatus":""},
{"speciesName":"Surf Scoter","latinName":"","conservationStatus":""},
{"speciesName":"Swan Goose (Chinese Goose)","latinName":"","conservationStatus":""},
{"speciesName":"Temmink's Stint","latinName":"","conservationStatus":""},
{"speciesName":"Trumpeter Finch","latinName":"","conservationStatus":""},
{"speciesName":"Wheatear (Greenland)","latinName":"","conservationStatus":""},
{"speciesName":"White Wagtail","latinName":"","conservationStatus":""},
{"speciesName":"White-rumped Sandpiper","latinName":"","conservationStatus":""},
{"speciesName":"Yellow Wagtail (Blue-headed)","latinName":"","conservationStatus":""},
{"speciesName":"Yellow Wagtail (flavissima)","latinName":"","conservationStatus":""},
{"speciesName":"Yellow-legged Gull","latinName":"","conservationStatus":""},
{"speciesName":"Yellow-rumped Warbler","latinName":"","conservationStatus":""},
{"speciesName":"Zebra Finch","latinName":"","conservationStatus":""},
{"speciesName":"hybrid Aythya","latinName":"","conservationStatus":""},
{"speciesName":"unidentified auk","latinName":"","conservationStatus":""},
{"speciesName":"unidentified diver","latinName":"","conservationStatus":""},
{"speciesName":"unidentified goose","latinName":"","conservationStatus":""},
{"speciesName":"unidentified grebe","latinName":"","conservationStatus":""},
{"speciesName":"unidentified shearwater","latinName":"","conservationStatus":""},
{"speciesName":"unidentified skua","latinName":"","conservationStatus":""},
{"speciesName":"unknown Stonechat sp","latinName":"","conservationStatus":""}
];